// <auto-generated />
using System;
using System.Collections.Generic;
using LanguageLab.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LanguageLab.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907114428_ChaptersAndExcludedWords")]
    partial class ChaptersAndExcludedWords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LanguageLab.Domain.Entities.Chapter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DictionaryId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WordsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryId", "Order")
                        .IsUnique();

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.ChapterWord", b =>
                {
                    b.Property<long>("ChapterId")
                        .HasColumnType("bigint");

                    b.Property<long>("WordPairId")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("ChapterId", "WordPairId");

                    b.HasIndex("WordPairId");

                    b.ToTable("ChapterWords");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.Dictionary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WordsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Dictionaries");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.DictionaryWord", b =>
                {
                    b.Property<long>("DictionaryId")
                        .HasColumnType("bigint");

                    b.Property<long>("WordPairId")
                        .HasColumnType("bigint");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.HasKey("DictionaryId", "WordPairId");

                    b.HasIndex("WordPairId");

                    b.HasIndex("DictionaryId", "Frequency");

                    b.ToTable("DictionaryWords", (string)null);
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.ExcludedWord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("WordPairId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WordPairId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "WordPairId")
                        .IsUnique();

                    b.ToTable("ExcludedWords");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.KnownWord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("WordPairId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WordPairId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "WordPairId")
                        .IsUnique();

                    b.ToTable("KnownWords");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.TelegramUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.Training", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DictionaryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryId");

                    b.HasIndex("UserId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.TrainingQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<long>>("OptionIds")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<long?>("PickedWordPairId")
                        .HasColumnType("bigint");

                    b.Property<long>("TrainingId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("WordPairId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WordPairId");

                    b.HasIndex("TrainingId", "Order");

                    b.ToTable("TrainingQuestions");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.UnknownWord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("WordPairId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WordPairId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "WordPairId")
                        .IsUnique();

                    b.ToTable("UnknownWords");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.WordPair", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("Words");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.WordProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Box")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLearned")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("WordPairId")
                        .HasColumnType("bigint");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WordPairId");

                    b.HasIndex("UserId", "WordPairId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsLearned", "DueAt");

                    b.ToTable("WordProgresses");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.Chapter", b =>
                {
                    b.HasOne("LanguageLab.Domain.Entities.Dictionary", "Dictionary")
                        .WithMany("Chapters")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.ChapterWord", b =>
                {
                    b.HasOne("LanguageLab.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Words")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLab.Domain.Entities.WordPair", "WordPair")
                        .WithMany()
                        .HasForeignKey("WordPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("WordPair");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.DictionaryWord", b =>
                {
                    b.HasOne("LanguageLab.Domain.Entities.Dictionary", "Dictionary")
                        .WithMany()
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLab.Domain.Entities.WordPair", "WordPair")
                        .WithMany()
                        .HasForeignKey("WordPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");

                    b.Navigation("WordPair");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.ExcludedWord", b =>
                {
                    b.HasOne("LanguageLab.Domain.Entities.TelegramUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLab.Domain.Entities.WordPair", "WordPair")
                        .WithMany()
                        .HasForeignKey("WordPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WordPair");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.KnownWord", b =>
                {
                    b.HasOne("LanguageLab.Domain.Entities.TelegramUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLab.Domain.Entities.WordPair", "WordPair")
                        .WithMany()
                        .HasForeignKey("WordPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WordPair");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.Training", b =>
                {
                    b.HasOne("LanguageLab.Domain.Entities.Dictionary", "Dictionary")
                        .WithMany()
                        .HasForeignKey("DictionaryId");

                    b.HasOne("LanguageLab.Domain.Entities.TelegramUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.TrainingQuestion", b =>
                {
                    b.HasOne("LanguageLab.Domain.Entities.Training", "Training")
                        .WithMany("Questions")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLab.Domain.Entities.TelegramUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLab.Domain.Entities.WordPair", "WordPair")
                        .WithMany()
                        .HasForeignKey("WordPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("User");

                    b.Navigation("WordPair");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.UnknownWord", b =>
                {
                    b.HasOne("LanguageLab.Domain.Entities.TelegramUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLab.Domain.Entities.WordPair", "WordPair")
                        .WithMany()
                        .HasForeignKey("WordPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WordPair");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.WordProgress", b =>
                {
                    b.HasOne("LanguageLab.Domain.Entities.TelegramUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLab.Domain.Entities.WordPair", "WordPair")
                        .WithMany()
                        .HasForeignKey("WordPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WordPair");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.Chapter", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.Dictionary", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("LanguageLab.Domain.Entities.Training", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
