/**
 * The English lexicon: every word form mapped to its lemmas, primary first — the same table the
 * server's book import uses. The data is public/lexicon/english-lexicon.txt, generated by
 * scripts/build_lexicon.py and never edited by hand. One line per form: a lone word is a lemma of
 * itself only; otherwise the form, then its lemmas, space-separated.
 */
export interface Lexicon {
  /** All lemmas of the form, primary first; [] when it is not an English word. Case-sensitive. */
  lemmasOf(form: string): readonly string[]
  /** The primary lemma, or null when the form is not an English word. */
  lemmaOf(form: string): string | null
}

export const LEXICON_URL = '/lexicon/english-lexicon.txt'

const LINE = /^[a-z]+( [a-z]+)*$/
const NONE: readonly string[] = Object.freeze([])

/**
 * Throws on any line that is not lowercase words separated by single spaces, and on an empty
 * text — so the SPA fallback page, served with status 200 for a missing file, is never mistaken
 * for a lexicon.
 */
export function parseLexicon(text: string): Lexicon {
  const table = new Map<string, readonly string[]>()

  for (const raw of text.split('\n')) {
    const line = raw.endsWith('\r') ? raw.slice(0, -1) : raw
    if (line === '') continue
    if (!LINE.test(line)) throw new Error(`Not a lexicon line: ${line.slice(0, 40)}`)

    const words = line.split(' ')
    table.set(words[0], words.length === 1 ? words : words.slice(1))
  }

  if (table.size === 0) throw new Error('The lexicon is empty')

  const lemmasOf = (form: string): readonly string[] => table.get(form) ?? NONE
  return {
    lemmasOf,
    lemmaOf: (form) => lemmasOf(form)[0] ?? null,
  }
}

let cached: Promise<Lexicon> | null = null

/**
 * The lexicon, fetched once per page load and shared by every caller. A failed fetch or parse is
 * not cached: the next call tries again.
 */
export function loadLexicon(): Promise<Lexicon> {
  if (cached === null) {
    const attempt = fetch(LEXICON_URL)
      .then((response) => {
        if (!response.ok) throw new Error(`Could not load the lexicon: HTTP ${response.status}`)
        return response.text()
      })
      .then(parseLexicon)

    cached = attempt
    attempt.catch(() => {
      if (cached === attempt) cached = null
    })
  }

  return cached
}
