// <auto-generated>
// Produced by generate_pronunciation_catalog.py. Do not hand-edit — rerun the script instead.
// </auto-generated>

namespace LanguageLab.Domain.Pronunciation;

public static partial class PronunciationCatalog
{
    public static readonly IReadOnlyList<SoundFamily> Families = new List<SoundFamily>
    {
        new("th-sounds", "TH sounds", new[] { "θ", "ð" }),
        new("r-sound", "The English R", new[] { "r" }),
        new("w-vs-v", "W vs V", new[] { "w", "v" }),
        new("ae-vs-eh", "Æ vs Ɛ (cat vs bed)", new[] { "æ", "ɛ" }),
        new("ih-vs-iy", "Ɪ vs Iː (ship vs sheep)", new[] { "ɪ", "iː" }),
        new("final-devoicing", "Voiced endings", new[] { "b", "d", "ɡ", "v", "z" }),
        new("ng-sound", "The NG sound", new[] { "ŋ" }),
        new("schwa", "The schwa", new[] { "ə" }),
        new("h-vs-g", "H vs G", new[] { "h", "ɡ" }),
    };

    public static readonly IReadOnlyList<PronunciationWord> Words = new List<PronunciationWord>
    {
        new("other", "/ˈʌðɚ/", "th-sounds", "other-us.wav", "other-uk.ogg"),
        new("think", "/ˈθɪŋk/", "th-sounds", "think-us.ogg", "think-uk.wav"),
        new("more", "/mɔːɹ/", "r-sound", "more-us.ogg", "more-uk.ogg"),
        new("when", "/wɛn/", "w-vs-v", "when-us.ogg", "when-uk.ogg"),
        new("very", "/ˈvɛɹi/", "w-vs-v", "very-us.ogg", "very-uk.ogg"),
        new("said", "/sɛd/", "ae-vs-eh", "said-us.ogg", "said-uk.wav"),
        new("man", "/ˈmæn/", "ae-vs-eh", "man-us.ogg", "man-uk.ogg"),
        new("many", "/ˈmɛni/", "ih-vs-iy", "many-us.ogg", "many-uk.ogg"),
        new("little", "/ˈlɪ.tl̩/", "ih-vs-iy", "little-us.wav", "little-uk.ogg"),
        new("give", "/ˈɡɪv/", "final-devoicing", "give-us.ogg", "give-uk.ogg"),
        new("big", "/bɪɡ/", "final-devoicing", "big-us.ogg", "big-uk.ogg"),
        new("job", "/d͡ʒɑb/", "final-devoicing", "job-us.ogg", "job-uk.ogg"),
        new("good", "/ɡʊd/", "final-devoicing", "good-us.ogg", "good-uk.ogg"),
        new("always", "/ˈɔl.weɪz/", "final-devoicing", "always-us.ogg", "always-uk.ogg"),
        new("long", "/lɑŋ/", "ng-sound", "long-us.wav", "long-uk.ogg"),
        new("people", "/ˈpi.pəl/", "schwa", "people-us.ogg", "people-uk.ogg"),
        new("how", "/haʊ/", "h-vs-g", "how-us.ogg", "how-uk.ogg"),
        new("go", "/ɡoʊ/", "h-vs-g", "go-us.ogg", "go-uk.ogg"),
    };
}
